In [1]:
import pandas as pd

In [7]:

df = pd.read_csv('../datasets/FARS_2016.txt',sep='\t')

In [9]:
df.describe()

,statenum,casenum,vnumber,pnumber,arf1,arf2,arf3,dayofweek,driverdrowsy,fhevent,...,seatpos,sex,vfatcount,numoccs,malcohol,drivpres,crashtype,criticaleventcat,criticalevent,trafflow
count,77612.000000,77612.000000,77612.000000,77612.000000,77612.000000,77612.000000,77612.000000,77612.00000,77612.0,77612.000000,...,77612.000000,77612.000000,77612.000000,77612.000000,77612.000000,77612.000000,77612.000000,77612.000000,77612.000000,77612.000000
mean,27.064062,768.605525,1.498145,1.641190,1.843465,0.634618,0.456824,4.16777,0.0,16.018438,...,14.765616,1.482271,0.664124,2.721628,0.167088,1.000155,45.571394,3.047377,40.847524,1.868075
std,16.373460,820.474050,1.556430,1.790937,8.119888,6.826353,6.556778,2.11002,0.0,12.286107,...,11.797114,1.111288,0.733851,6.983128,0.373056,0.090525,35.903381,1.445843,28.899477,1.296584
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.00000,0.0,1.000000,...,11.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
25%,12.000000,200.000000,1.000000,1.000000,0.000000,0.000000,0.000000,2.00000,0.0,12.000000,...,11.000000,1.000000,0.000000,1.000000,0.000000,1.000000,10.000000,2.000000,13.000000,1.000000
50%,26.000000,471.000000,1.000000,1.000000,0.000000,0.000000,0.000000,4.00000,0.0,12.000000,...,11.000000,1.000000,1.000000,2.000000,0.000000,1.000000,50.000000,3.000000,51.000000,1.000000
75%,42.000000,945.000000,2.000000,2.000000,0.000000,0.000000,0.000000,6.00000,0.0,12.000000,...,13.000000,2.000000,1.000000,3.000000,0.000000,1.000000,83.000000,4.000000,62.000000,3.000000
max,56.000000,3503.000000,64.000000,52.000000,99.000000,99.000000,99.000000,7.00000,0.0,99.000000,...,99.000000,9.000000,9.000000,99.000000,1.000000,9.000000,99.000000,9.000000,99.000000,9.000000